// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import Desafio1Controller from "./desafio1_controller"
import ConfigModalController from "./config_modal_controller"

application.register("hello", HelloController)
application.register("desafio1", Desafio1Controller)
application.register("config_modal", ConfigModalController)
